export const RoutesList = {
  app: "/",
  login: "login",
  signup: "signup",
  contactUs: "contact-us",
  facebookAccount: "https://facebook.com",
  twitterAccount: "https://instagram.com",
  instagramAccount: "https://twitter.com",
  githubAccount: "https://github.com",
  cartView: "cart-view",
  passwordReset: "password-reset",
  navigationBar: {
    home: "/",
    categories: "categories",
    products: "products-list",
    aboutUs: "about-us",
  },
  categories: {
    list: "categories",
    productView: "product-preview",
    house: "house",
    mobileAndElectronic: "mobile-and-electronic",
    books: "books",
    fashios: "fashios",
    games: "games",
    homeTools: "home-tools",
    SportsAccesoress: "Sports-accesoress",
    babyProducts: "baby-products",
    kitchenProducts: "kitchen-products",
    gifts: "gifts",
    betFoods: "bet-foods",
  },
  productsList: "products-list",
  productPreviewPage: "preview-page",
  cart: "cart",
  checkout: "checkout",
  accountPageMobile: "account-mobile",
  wishlist: "white-list",
  profile: {
    profile: "profile",
    address: "address",
    wishlist: "white-list",
    personalInfo: "personal-info",
    orders: "orders-list",
    payments: "payments-info",
  },
};
