export let dummyData = [
  {
    categoryName: "smartphones",
    categoryClassIcon: "fi fi-rr-mobile-notch",
    categoryDescription: "smartphones and accessories ios or android",
    backgroundColor: "#ECC5FB",
    color: "#421454",
  },
  {
    categoryName: "laptops",
    categoryClassIcon: "fi fi-rr-laptop",
    categoryDescription: "laptops and accessories ios or android or others",
    backgroundColor: "#FFB3B3",
    color: "#570A57",
  },
  {
    categoryName: "fragrances",
    categoryClassIcon: "fi fi-rr-f",
    categoryDescription: "fragrances and accessories ",
    backgroundColor: "#F7ECDE",
    color: "#500909",
  },
  {
    categoryName: "skincare",
    categoryClassIcon: "fi fi-rr-cream",
    categoryDescription: "skincare and accessories ",
    backgroundColor: "#C1EFFF",
    color: "#002855",
  },
  {
    categoryName: "groceries",
    categoryClassIcon: "fi fi-rr-shop",
    categoryDescription: "groceries and accessories ",
    backgroundColor: "#9ED2C6",
    color: "#083e50",
  },
  {
    categoryName: "home-decoration",
    categoryClassIcon: "fi fi-rr-home",
    categoryDescription: "home and decoration and his accessories ",
    backgroundColor: "#7D9D9C",
    color: "#094a3b",
  },
  {
    categoryName: "furniture",
    categoryClassIcon: "fi fi-rr-chair",
    categoryDescription: "furniture and his accessories ",
    backgroundColor: "#FFD9C0",
    color: "#6e3815",
  },
  {
    categoryName: "tops",
    categoryClassIcon: "fi fi-rr-dice-three",
    categoryDescription: "tops and his accessories ",
    backgroundColor: "#8CC0DE",
    color: "#0a254e",
  },
  {
    categoryName: "mens fashion",
    categoryClassIcon: "fi fi-rr-man-head",
    categoryDescription: "mens fashion and his accessories ",
    backgroundColor: "#AD8B73",
    color: "#401f08",
  },
  {
    categoryName: "womens fashion",
    categoryClassIcon: "fi fi-rr-woman-head",
    categoryDescription: "womens fashion and his accessories ",
    backgroundColor: "#F9CEEE",
    color: "#4a250c",
  },

  {
    categoryName: "lighting",
    categoryClassIcon: "fi fi-rr-bulb",
    categoryDescription: "womens fashion and his accessories ",
    backgroundColor: "#FFF89A",
    color: "#423e07",
  },
];
